stages:
  - quality
  - publish

python-publish:
  stage: publish
  before_script:
    - chmod +x ./scripts/python_install.sh
    - ./scripts/python_install.sh
  script:
    - chmod +x ./scripts/python_publish.sh
    - ./scripts/python_publish.sh
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/

python-tests:
  stage: quality
  image: python:3.6-slim-buster
  before_script:
    - chmod +x ./scripts/python_install.sh
    - ./scripts/python_install.sh
  script:
    - chmod +x ./scripts/python_quality.sh
    - ./scripts/python_quality.sh
  artifacts:
    untracked: false
    expire_in: "30 days"
    reports:
      junit:
        - "**/*.xml"
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite_common/**/*
