stages:
  - quality
  - publish

python-publish:
  stage: publish
  variables:
    PACKAGE_NAME: labonneboite-common
    PACKAGE_VERSION: $CI_COMMIT_TAG
  script:
    - chmod +x ../scripts/python_publish.sh
    - ../scripts/python_publish.sh
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/

python-tests:
  stage: quality
  image: python:3.6-slim-buster
  script:
    - chmod +x ./scripts/python_quality.sh
    - ./scripts/python_quality.sh
  artifacts:
    untracked: false
    expire_in: "30 days"
    reports:
      junit:
        - "**/testResults/*.xml"
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite_common/**/*

publish-prod:
  extends: .publish-docker
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/

publish-dev:
  extends: .publish-docker
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-rc\.\d+(\+.*)?$/
