stages:
  - build
  - tests
  - publish

# test it
tests:
  stage: tests
  image: python:3.6-slim-buster
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite_common/**/*
  before_script:
    - pip install -r requirements.dev.txt
  script:
    - chmod +x .ci/python-test.sh
    - .ci/python-test.sh
