stages:
  - build
  - quality
  - publish

# test it
# python-build:
#   stage: quality
#   before_script:
#     - pip install -r requirements.dev.txt
#   script:
#     - chmod +x ./ci/python_quality.sh
#     - ./ci/python_quality.sh
#   rules:
#     - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
#       changes:
#         - labonneboite_common/**/*

python-tests:
  stage: quality
  image: python:3.6-slim-buster
  before_script:
    - pip install -r requirements.dev.txt
  script:
    - chmod +x ./scripts/python_quality.sh
    - ./scripts/python_quality.sh
  artifacts:
    untracked: false
    expire_in: "30 days"
    reports:
      junit:
        - "**/testResults/*.xml"
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite_common/**/*
