version: "3.7"

services:

  app:
    restart: "no"
    build:
      context: .
      dockerfile: ./docker/v3.10/Dockerfile
    volumes:
      - ./testResults:/labonneboite_common/testResults
    entrypoint: /bin/bash ./entrypoints/test.sh

