docs_dir: docs

theme:
  name: material
  font:
    text: "Montserrat"
    code: "Montserrat Sans"
  features:
    # - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - toc.follow
    - content.code.copy
    # - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  homepage: https://labonneboite-m-documentation.beta.pole-emploi.fr

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Do your stuff below

repo_name: labonneboite-v1-common
repo_url: https://git.beta.pole-emploi.fr/lbb/lbb-common
# Do your stuff below
site_name: La Bonne Boite v1 - Common
site_description: "La Bonne Boite v1 - Data model and utils"
site_author: "La Bonne Boite"

nav:
  - index.md
